--
-- Select Simples
--

SELECT ID_ESTADO, NM_ESTADO, SG_ESTADO FROM T_RHSTU_ESTADO ORDER BY SG_ESTADO;

--
-- Select Simples "Produto Cartesiano" (Column Ambiguosly)
--

SELECT SG_ESTADO, NM_ESTADO, ID_ESTADO, ID_CIDADE, NM_CIDADE, CD_IBGE, NR_DDD
FROM T_RHSTU_ESTADO, T_RHSTU_CIDADE 
ORDER BY SG_ESTADO;

--
-- Produto Cartesiano
--

SELECT E.SG_ESTADO, E.NM_ESTADO, E.ID_ESTADO,
C.ID_ESTADO, C.ID_CIDADE, C.NM_CIDADE, C.CD_IBGE, C.NR_DDD
FROM T_RHSTU_ESTADO E, T_RHSTU_CIDADE C 
ORDER BY SG_ESTADO;


--
-- Inner Join
--

SELECT E.SG_ESTADO, E.NM_ESTADO, E.ID_ESTADO,
C.ID_ESTADO, C.ID_CIDADE, C.NM_CIDADE, C.CD_IBGE, C.NR_DDD
FROM T_RHSTU_ESTADO E INNER JOIN T_RHSTU_CIDADE C
ON(E.ID_ESTADO = C.ID_ESTADO)
ORDER BY SG_ESTADO;

--
-- Left Join
--

SELECT E.SG_ESTADO, E.NM_ESTADO,
C.NM_CIDADE, C.CD_IBGE, C.NR_DDD
FROM T_RHSTU_ESTADO E LEFT JOIN T_RHSTU_CIDADE C
ON(E.ID_ESTADO = C.ID_ESTADO)
ORDER BY SG_ESTADO;

--
-- Right Join
--

SELECT E.SG_ESTADO, E.NM_ESTADO,
C.NM_CIDADE, C.CD_IBGE, C.NR_DDD
FROM T_RHSTU_CIDADE C RIGHT JOIN T_RHSTU_ESTADO E
ON(E.ID_ESTADO = C.ID_ESTADO)
ORDER BY SG_ESTADO;


--
-- Padr�o Oracle Inner Join
--

SELECT E.SG_ESTADO, E.NM_ESTADO,
C.NM_CIDADE, C.CD_IBGE, C.NR_DDD
FROM T_RHSTU_ESTADO E, T_RHSTU_CIDADE C
WHERE E.ID_ESTADO = C.ID_ESTADO
ORDER BY SG_ESTADO;

--
-- Padr�o Oracle Outer Join
--

SELECT E.SG_ESTADO, E.NM_ESTADO,
C.NM_CIDADE, C.CD_IBGE, C.NR_DDD
FROM T_RHSTU_ESTADO E, T_RHSTU_CIDADE C
WHERE E.ID_ESTADO = C.ID_ESTADO(+)
ORDER BY SG_ESTADO;

--
-- Padr�o Oracle Join 1TDSVJ
-- Select Join com Estado Cidade e Bairro
--

SELECT E.SG_ESTADO, E.NM_ESTADO,
C.NM_CIDADE, C.CD_IBGE, C.NR_DDD,
B.NM_BAIRRO, B.NM_ZONA_BAIRRO
FROM T_RHSTU_ESTADO E LEFT JOIN T_RHSTU_CIDADE C
ON(E.ID_ESTADO = C.ID_ESTADO) LEFT JOIN T_RHSTU_BAIRRO B
ON(C.ID_CIDADE = B.ID_CIDADE)
ORDER BY E.SG_ESTADO, C.NM_CIDADE, B.NM_BAIRRO;

--
-- Select Join com Estado, Cidade, Bairro e Logradouro
--

SELECT E.SG_ESTADO, E.NM_ESTADO,
C.NM_CIDADE, C.CD_IBGE, C.NR_DDD,
B.NM_BAIRRO, B.NM_ZONA_BAIRRO,
L.NM_LOGRADOURO, L.NR_CEP
FROM T_RHSTU_ESTADO E LEFT JOIN T_RHSTU_CIDADE C
ON(E.ID_ESTADO = C.ID_ESTADO) LEFT JOIN T_RHSTU_BAIRRO B
ON(C.ID_CIDADE = B.ID_CIDADE) LEFT JOIN T_RHSTU_LOGRADOURO L
ON(B.ID_BAIRRO = L.ID_BAIRRO)
ORDER BY E.SG_ESTADO, C.NM_CIDADE, B.NM_BAIRRO;

--
-- Select Join com Estado, Cidade, Bairro, Logradouro e Endere�o Paciente
--

SELECT E.SG_ESTADO, E.NM_ESTADO,
C.NM_CIDADE, C.CD_IBGE, C.NR_DDD,
B.NM_BAIRRO, B.NM_ZONA_BAIRRO,
L.NM_LOGRADOURO, L.NR_CEP,
LP.NR_LOGRADOURO, LP.DS_COMPLEMENTO_NUMERO, LP.DS_PONTO_REFERENCIA, LP.DT_INICIO, LP.DT_FIM,
P.NM_PACIENTE, P.NR_CPF, P.DT_NASCIMENTO,P.DS_ESTADO_CIVIL
FROM T_RHSTU_ESTADO E LEFT JOIN T_RHSTU_CIDADE C
ON(E.ID_ESTADO = C.ID_ESTADO) LEFT JOIN T_RHSTU_BAIRRO B
ON(C.ID_CIDADE = B.ID_CIDADE) LEFT JOIN T_RHSTU_LOGRADOURO L
ON(B.ID_BAIRRO = L.ID_BAIRRO) LEFT JOIN T_RHSTU_ENDERECO_PACIENTE LP
ON(L.ID_LOGRADOURO = LP.ID_LOGRADOURO) LEFT JOIN T_RHSTU_PACIENTE P
ON(LP.ID_PACIENTE = P.ID_PACIENTE)
ORDER BY E.SG_ESTADO, C.NM_CIDADE, B.NM_BAIRRO, L.NM_LOGRADOURO, P.NM_PACIENTE;


--
-- Select Inner Join com Estado, Cidade, Bairro, Logradouro e Endere�o Paciente
--

SELECT E.SG_ESTADO, E.NM_ESTADO,
C.NM_CIDADE, C.CD_IBGE, C.NR_DDD,
B.NM_BAIRRO, B.NM_ZONA_BAIRRO,
L.NM_LOGRADOURO, L.NR_CEP,
LP.NR_LOGRADOURO, LP.DS_COMPLEMENTO_NUMERO, LP.DS_PONTO_REFERENCIA, LP.DT_INICIO, LP.DT_FIM,
P.NM_PACIENTE, P.NR_CPF, P.DT_NASCIMENTO,P.DS_ESTADO_CIVIL
FROM T_RHSTU_ESTADO E INNER JOIN T_RHSTU_CIDADE C
ON(E.ID_ESTADO = C.ID_ESTADO) INNER JOIN T_RHSTU_BAIRRO B
ON(C.ID_CIDADE = B.ID_CIDADE) INNER JOIN T_RHSTU_LOGRADOURO L
ON(B.ID_BAIRRO = L.ID_BAIRRO) INNER JOIN T_RHSTU_ENDERECO_PACIENTE LP
ON(L.ID_LOGRADOURO = LP.ID_LOGRADOURO) INNER JOIN T_RHSTU_PACIENTE P
ON(LP.ID_PACIENTE = P.ID_PACIENTE)
ORDER BY E.SG_ESTADO, C.NM_CIDADE, B.NM_BAIRRO, L.NM_LOGRADOURO, P.NM_PACIENTE;

--
-- Conferindo
--

SELECT COUNT(*) FROM T_RHSTU_PACIENTE;

--
-- CriandoView Logica
--
CREATE OR REPLACE VIEW V_DADOS_RHSTU_PACIENTE AS
SELECT E.SG_ESTADO, E.NM_ESTADO,
C.NM_CIDADE, C.CD_IBGE, C.NR_DDD,
B.NM_BAIRRO, B.NM_ZONA_BAIRRO,
L.NM_LOGRADOURO, L.NR_CEP,
LP.NR_LOGRADOURO, LP.DS_COMPLEMENTO_NUMERO, LP.DS_PONTO_REFERENCIA, LP.DT_INICIO, LP.DT_FIM,
P.NM_PACIENTE, P.NR_CPF, P.DT_NASCIMENTO,P.DS_ESTADO_CIVIL
FROM T_RHSTU_ESTADO E INNER JOIN T_RHSTU_CIDADE C
ON(E.ID_ESTADO = C.ID_ESTADO) INNER JOIN T_RHSTU_BAIRRO B
ON(C.ID_CIDADE = B.ID_CIDADE) INNER JOIN T_RHSTU_LOGRADOURO L
ON(B.ID_BAIRRO = L.ID_BAIRRO) INNER JOIN T_RHSTU_ENDERECO_PACIENTE LP
ON(L.ID_LOGRADOURO = LP.ID_LOGRADOURO) INNER JOIN T_RHSTU_PACIENTE P
ON(LP.ID_PACIENTE = P.ID_PACIENTE)
ORDER BY E.SG_ESTADO, C.NM_CIDADE, B.NM_BAIRRO, L.NM_LOGRADOURO, P.NM_PACIENTE;

SELECT * FROM V_DADOS_RHSTU_PACIENTE;